// Generates src/schema-sql.ts: the idempotent DDL (CREATE ... IF NOT EXISTS)
// of src/schema.ts as a string constant, so the built package needs no .sql file.
// Run: pnpm generate (inside kimaki).

import { execFile } from 'node:child_process'
import fs from 'node:fs'
import path from 'node:path'
import { promisify } from 'node:util'

const execFileAsync = promisify(execFile)
const root = process.cwd()
const outputPath = path.join(root, 'src/schema-sql.ts')

function makeIdempotent(sql: string) {
  return sql
    .split('\n')
    .map((line) => {
      return line
        .replace(/^CREATE TABLE\b(?! IF NOT EXISTS)/i, 'CREATE TABLE IF NOT EXISTS')
        .replace(/^CREATE UNIQUE INDEX\b(?! IF NOT EXISTS)/i, 'CREATE UNIQUE INDEX IF NOT EXISTS')
        .replace(/^CREATE INDEX\b(?! IF NOT EXISTS)/i, 'CREATE INDEX IF NOT EXISTS')
    })
    .join('\n')
}

async function main() {
  console.log('Exporting Drizzle schema SQL...')
  const { stdout } = await execFileAsync('pnpm', ['drizzle-kit', 'export'], { cwd: root })
  const rawSql = stdout.trim()
  const firstLine = rawSql.split('\n').find((line) => line.trim() !== '')
  if (!firstLine || !/^CREATE\s+(TABLE|INDEX|UNIQUE\s+INDEX)\b/i.test(firstLine)) {
    throw new Error('drizzle-kit export did not print SQL to stdout')
  }
  console.log(`Writing ${outputPath}...`)
  const sql = makeIdempotent(rawSql)
  fs.writeFileSync(
    outputPath,
    [
      '// Generated by pnpm generate from src/schema.ts. Do not edit.',
      '',
      `export const SCHEMA_SQL = ${JSON.stringify(sql)}`,
      '',
    ].join('\n'),
  )
  console.log('Done.')
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
