export type TraceItemType = 'event' | 'log'

export type TraceLogItem = {
  id: string
  type: TraceItemType
  timestamp: string
  badge: string
  level?: 'info' | 'warn' | 'error'
  service?: string
  tags?: string[]
  message: string
  details?: Record<string, unknown>
}

export type TraceMetric = {
  label: string
  value: string
  tooltip: string
  series: number[]
}

export type TraceSpan = {
  id: string
  parentId: string | null
  title: string
  service: string
  kind: 'server' | 'client' | 'db' | 'worker' | 'cache'
  startNs: number
  durationNs: number
  startLabel: string
  durationLabel: string
  status: 'ok' | 'error'
  summary: string
  namespace?: string
  pod?: string
  container?: string
  runtime?: string
  host?: string
  destination?: string
  attributes: Record<string, unknown>
  logs: TraceLogItem[]
}

export type TraceExample = {
  id: string
  traceId: string
  title: string
  service: string
  environment: string
  startedAt: string
  durationLabel: string
  status: 'healthy' | 'degraded'
  sourceId: string
  metrics: TraceMetric[]
  spans: TraceSpan[]
}

export const traceExamples: TraceExample[] = [
  {
    id: 'trace-checkout',
    traceId: '9acb5146d6e7ef2aab22000001a2c991',
    title: 'POST /api/checkout',
    service: 'checkout-api',
    environment: 'production',
    startedAt: '2026-03-26 22:03:14.822 UTC',
    durationLabel: '418 ms',
    status: 'degraded',
    sourceId: 'src_checkout',
    metrics: [
      {
        label: 'Requests',
        value: '184 rps',
        tooltip: 'Average rate of incoming HTTP requests',
        series: [12, 16, 15, 22, 24, 18, 19, 25, 21, 17, 20, 18],
      },
      {
        label: 'Errors',
        value: '2.48%',
        tooltip: 'Percentage of incoming requests that returned an error',
        series: [1, 3, 2, 5, 4, 2, 1, 4, 2, 3, 2, 1],
      },
      {
        label: 'Duration',
        value: '418 ms',
        tooltip: 'Average time to respond to an incoming request',
        series: [8, 10, 11, 15, 16, 14, 13, 17, 16, 12, 11, 10],
      },
    ],
    spans: [
      {
        id: 'span-root-checkout',
        parentId: null,
        title: 'POST /api/checkout',
        service: 'checkout-api',
        kind: 'server',
        startNs: 0,
        durationNs: 418,
        startLabel: '0 ms',
        durationLabel: '418 ms',
        status: 'error',
        summary: 'Accepts the checkout request, validates the basket, and orchestrates downstream spans.',
        namespace: 'prod-store',
        pod: 'checkout-api-74f79c6df6-q9rxp',
        container: 'checkout-api',
        runtime: 'nodejs 22',
        host: 'ip-10-30-12-44.ec2.internal',
        attributes: {
          'http.method': 'POST',
          'http.route': '/api/checkout',
          'http.status_code': 500,
          'user.id': 'usr_12891',
          'cart.id': 'cart_77f0',
        },
        logs: [
          {
            id: 'log-root-checkout-1',
            type: 'log',
            timestamp: '2026-03-26 22:03:14.829 UTC',
            badge: 'Log',
            level: 'info',
            service: 'checkout-api',
            message: 'Started checkout orchestration for cart_77f0.',
            details: {
              logger: 'checkout-orchestrator',
              cartId: 'cart_77f0',
              customerId: 'usr_12891',
              checkoutVersion: '2026.03.26.4',
            },
          },
          {
            id: 'event-root-checkout-1',
            type: 'event',
            timestamp: '2026-03-26 22:03:15.219 UTC',
            badge: 'Event',
            tags: ['exception', 'rollback'],
            message: 'Rolled back order transaction after payment gateway timeout.',
            details: {
              exception: 'PaymentProviderTimeoutError',
              rollbackStep: 'order_transaction',
              retryable: true,
            },
          },
        ],
      },
      {
        id: 'span-basket',
        parentId: 'span-root-checkout',
        title: 'validate basket',
        service: 'checkout-api',
        kind: 'worker',
        startNs: 18,
        durationNs: 62,
        startLabel: '18 ms',
        durationLabel: '62 ms',
        status: 'ok',
        summary: 'Normalizes basket items and verifies inventory reservations before payment.',
        namespace: 'prod-store',
        pod: 'checkout-api-74f79c6df6-q9rxp',
        container: 'checkout-api',
        runtime: 'nodejs 22',
        host: 'ip-10-30-12-44.ec2.internal',
        attributes: {
          'basket.items': 4,
          'inventory.strategy': 'reservation-lock',
        },
        logs: [
          {
            id: 'log-basket-1',
            type: 'log',
            timestamp: '2026-03-26 22:03:14.892 UTC',
            badge: 'Log',
            level: 'info',
            service: 'checkout-api',
            message: 'Inventory validation completed for 4 basket rows.',
            details: {
              validator: 'inventory-reservations',
              basketItems: 4,
              missingReservations: 0,
            },
          },
        ],
      },
      {
        id: 'span-postgres',
        parentId: 'span-root-checkout',
        title: 'INSERT orders',
        service: 'orders-db',
        kind: 'db',
        startNs: 92,
        durationNs: 96,
        startLabel: '92 ms',
        durationLabel: '96 ms',
        status: 'ok',
        summary: 'Writes the draft order and line items inside a database transaction.',
        namespace: 'prod-store',
        pod: 'orders-db-0',
        container: 'postgres',
        runtime: 'postgresql 16',
        host: 'postgres-primary.internal',
        attributes: {
          'db.system': 'postgresql',
          'db.operation': 'INSERT',
          'db.statement': 'insert into orders (...) values (...)',
        },
        logs: [
          {
            id: 'event-postgres-1',
            type: 'event',
            timestamp: '2026-03-26 22:03:15.001 UTC',
            badge: 'Event',
            tags: ['sql'],
            message: 'Inserted order header and 4 line items in a single transaction.',
            details: {
              transactionId: 'tx_0af8b13',
              rowsWritten: 5,
              primaryTable: 'orders',
            },
          },
        ],
      },
      {
        id: 'span-payment',
        parentId: 'span-root-checkout',
        title: 'POST stripe /payment_intents',
        service: 'payment-gateway',
        kind: 'client',
        startNs: 196,
        durationNs: 172,
        startLabel: '196 ms',
        durationLabel: '172 ms',
        status: 'error',
        summary: 'Calls Stripe to confirm the payment intent and waits for an authorization response.',
        namespace: 'edge',
        runtime: 'nodejs 22',
        host: 'stripe-gateway',
        destination: 'payments/stripe',
        attributes: {
          'http.method': 'POST',
          'http.url': 'https://api.stripe.com/v1/payment_intents',
          'http.status_code': 504,
          'net.peer.name': 'api.stripe.com',
        },
        logs: [
          {
            id: 'log-payment-1',
            type: 'log',
            timestamp: '2026-03-26 22:03:15.104 UTC',
            badge: 'Log',
            level: 'warn',
            service: 'payment-gateway',
            message: 'Gateway timeout threshold crossed while waiting for Stripe.',
            details: {
              provider: 'stripe',
              timeoutMs: 1500,
              attempt: 1,
            },
          },
          {
            id: 'event-payment-1',
            type: 'event',
            timestamp: '2026-03-26 22:03:15.188 UTC',
            badge: 'Event',
            tags: ['exception', 'timeout'],
            message: 'The payment provider did not respond before the request deadline.',
            details: {
              exception: 'AbortError',
              deadlineMs: 1500,
              providerStatus: 'unknown',
            },
          },
        ],
      },
      {
        id: 'span-analytics',
        parentId: 'span-root-checkout',
        title: 'publish checkout event',
        service: 'event-bus',
        kind: 'client',
        startNs: 284,
        durationNs: 41,
        startLabel: '284 ms',
        durationLabel: '41 ms',
        status: 'ok',
        summary: 'Streams a checkout.attempted event for dashboards and customer journey analytics.',
        namespace: 'prod-store',
        runtime: 'nodejs 22',
        host: 'kafka-broker-01',
        destination: 'analytics/checkout-attempted',
        attributes: {
          'messaging.system': 'kafka',
          'messaging.destination': 'checkout.attempted',
        },
        logs: [
          {
            id: 'log-analytics-1',
            type: 'log',
            timestamp: '2026-03-26 22:03:15.132 UTC',
            badge: 'Log',
            level: 'info',
            service: 'event-bus',
            message: 'Published checkout.attempted event to analytics topic.',
            details: {
              topic: 'checkout.attempted',
              partition: 8,
              offset: 349221,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'trace-search',
    traceId: '54fc8e1bd6b44c54a72700000289df21',
    title: 'GET /search/products',
    service: 'catalog-api',
    environment: 'production',
    startedAt: '2026-03-26 22:04:48.103 UTC',
    durationLabel: '182 ms',
    status: 'healthy',
    sourceId: 'src_catalog',
    metrics: [
      {
        label: 'Requests',
        value: '402 rps',
        tooltip: 'Average rate of incoming HTTP requests',
        series: [16, 18, 20, 22, 24, 23, 21, 19, 18, 17, 18, 20],
      },
      {
        label: 'Errors',
        value: '0.32%',
        tooltip: 'Percentage of incoming requests that returned an error',
        series: [1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 1],
      },
      {
        label: 'Duration',
        value: '182 ms',
        tooltip: 'Average time to respond to an incoming request',
        series: [7, 8, 9, 9, 10, 10, 9, 8, 7, 7, 8, 8],
      },
    ],
    spans: [
      {
        id: 'span-root-search',
        parentId: null,
        title: 'GET /search/products',
        service: 'catalog-api',
        kind: 'server',
        startNs: 0,
        durationNs: 182,
        startLabel: '0 ms',
        durationLabel: '182 ms',
        status: 'ok',
        summary: 'Handles a faceted search request and combines Elasticsearch hits with pricing.',
        namespace: 'prod-catalog',
        pod: 'catalog-api-7c7c49476f-kj2zh',
        container: 'catalog-api',
        runtime: 'nodejs 22',
        host: 'ip-10-30-18-11.ec2.internal',
        attributes: {
          'http.method': 'GET',
          'http.route': '/search/products',
          'http.status_code': 200,
          q: 'trail running shoes',
        },
        logs: [
          {
            id: 'log-search-1',
            type: 'log',
            timestamp: '2026-03-26 22:04:48.111 UTC',
            badge: 'Log',
            level: 'info',
            service: 'catalog-api',
            message: 'Search request normalized to 3 filters and 20 result rows.',
            details: {
              query: 'trail running shoes',
              filters: ['brand:northline', 'price:<200', 'gender:women'],
              resultCount: 20,
            },
          },
        ],
      },
      {
        id: 'span-es-query',
        parentId: 'span-root-search',
        title: 'POST elasticsearch /products/_search',
        service: 'search-cluster',
        kind: 'client',
        startNs: 16,
        durationNs: 74,
        startLabel: '16 ms',
        durationLabel: '74 ms',
        status: 'ok',
        summary: 'Runs the weighted product search against the primary Elasticsearch cluster.',
        runtime: 'elasticsearch 8',
        host: 'es-prod-01',
        destination: 'search/elasticsearch',
        attributes: {
          'db.system': 'elasticsearch',
          'db.operation': 'search',
          'http.status_code': 200,
        },
        logs: [
          {
            id: 'event-es-query-1',
            type: 'event',
            timestamp: '2026-03-26 22:04:48.151 UTC',
            badge: 'Event',
            tags: ['search'],
            message: 'Primary cluster returned 20 hits with a 41 ms shard max.',
            details: {
              shards: 6,
              tookMs: 41,
              totalHits: 20,
            },
          },
        ],
      },
      {
        id: 'span-price-cache',
        parentId: 'span-root-search',
        title: 'GET redis product prices',
        service: 'pricing-cache',
        kind: 'cache',
        startNs: 102,
        durationNs: 24,
        startLabel: '102 ms',
        durationLabel: '24 ms',
        status: 'ok',
        summary: 'Fetches cached pricing blobs for the hit set to avoid a database roundtrip.',
        runtime: 'redis 7',
        host: 'redis-pricing-01',
        destination: 'cache/prices',
        attributes: {
          'db.system': 'redis',
          'db.operation': 'MGET',
          'cache.hit_count': 20,
        },
        logs: [
          {
            id: 'log-price-cache-1',
            type: 'log',
            timestamp: '2026-03-26 22:04:48.178 UTC',
            badge: 'Log',
            level: 'info',
            service: 'pricing-cache',
            message: 'Served 20 product pricing entries from Redis.',
            details: {
              cacheHits: 20,
              cacheMisses: 0,
              keyPattern: 'price:*',
            },
          },
        ],
      },
    ],
  },
  {
    id: 'trace-worker',
    traceId: '8110a67ac44a3f4bb3e50000031cf006',
    title: 'sync invoices to ERP',
    service: 'billing-worker',
    environment: 'staging',
    startedAt: '2026-03-26 22:07:02.044 UTC',
    durationLabel: '1.24 s',
    status: 'healthy',
    sourceId: 'src_billing',
    metrics: [
      {
        label: 'Requests',
        value: '27 jobs/min',
        tooltip: 'Average rate of worker jobs finishing per minute',
        series: [6, 8, 7, 9, 10, 8, 7, 9, 8, 7, 8, 7],
      },
      {
        label: 'Errors',
        value: '0.00%',
        tooltip: 'Percentage of worker jobs that ended in error',
        series: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      },
      {
        label: 'Duration',
        value: '1.24 s',
        tooltip: 'Average time for the worker to finish one invoice sync batch',
        series: [10, 11, 10, 12, 13, 11, 10, 11, 12, 10, 9, 10],
      },
    ],
    spans: [
      {
        id: 'span-root-worker',
        parentId: null,
        title: 'sync invoices to ERP',
        service: 'billing-worker',
        kind: 'worker',
        startNs: 0,
        durationNs: 1240,
        startLabel: '0 ms',
        durationLabel: '1.24 s',
        status: 'ok',
        summary: 'Consumes a billing queue batch and sends normalized invoices to the ERP adapter.',
        namespace: 'staging-billing',
        pod: 'billing-worker-6d94d78db4-rbgks',
        container: 'billing-worker',
        runtime: 'nodejs 22',
        host: 'ip-10-30-29-19.ec2.internal',
        attributes: {
          'messaging.system': 'sqs',
          'messaging.destination': 'invoice-sync',
          'batch.size': 12,
        },
        logs: [
          {
            id: 'log-worker-1',
            type: 'log',
            timestamp: '2026-03-26 22:07:02.049 UTC',
            badge: 'Log',
            level: 'info',
            service: 'billing-worker',
            message: 'Picked up 12 invoice records from the invoice-sync queue.',
            details: {
              queue: 'invoice-sync',
              batchSize: 12,
              attempt: 1,
            },
          },
        ],
      },
      {
        id: 'span-normalize',
        parentId: 'span-root-worker',
        title: 'normalize invoice payloads',
        service: 'billing-worker',
        kind: 'worker',
        startNs: 32,
        durationNs: 208,
        startLabel: '32 ms',
        durationLabel: '208 ms',
        status: 'ok',
        summary: 'Converts internal billing records into the ERP invoice shape.',
        runtime: 'nodejs 22',
        host: 'ip-10-30-29-19.ec2.internal',
        attributes: {
          'records.processed': 12,
          'records.skipped': 0,
        },
        logs: [
          {
            id: 'event-normalize-1',
            type: 'event',
            timestamp: '2026-03-26 22:07:02.221 UTC',
            badge: 'Event',
            tags: ['mapping'],
            message: 'Normalization map loaded successfully for the ERP schema version.',
            details: {
              schemaVersion: 'erp-v4',
              recordsMapped: 12,
              warnings: 0,
            },
          },
        ],
      },
      {
        id: 'span-erp-upload',
        parentId: 'span-root-worker',
        title: 'POST /erp/invoices/bulk',
        service: 'erp-adapter',
        kind: 'client',
        startNs: 286,
        durationNs: 782,
        startLabel: '286 ms',
        durationLabel: '782 ms',
        status: 'ok',
        summary: 'Uploads the normalized invoice batch to the ERP bulk API.',
        runtime: 'nodejs 22',
        host: 'erp-adapter.internal',
        destination: 'erp/invoice-bulk',
        attributes: {
          'http.method': 'POST',
          'http.route': '/erp/invoices/bulk',
          'http.status_code': 202,
          'invoice.count': 12,
        },
        logs: [
          {
            id: 'log-erp-upload-1',
            type: 'log',
            timestamp: '2026-03-26 22:07:02.947 UTC',
            badge: 'Log',
            level: 'info',
            service: 'erp-adapter',
            message: 'ERP adapter accepted the invoice batch for asynchronous reconciliation.',
            details: {
              adapterJobId: 'erp_job_9914',
              acceptedAt: '2026-03-26T22:07:02.947Z',
              invoiceCount: 12,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'trace-service-fanout',
    traceId: '2ca4ce24aa4411b4d2f7000004bc9012',
    title: 'GET /dashboard/home',
    service: 'frontend-bff',
    environment: 'production',
    startedAt: '2026-03-26 22:12:11.019 UTC',
    durationLabel: '612 ms',
    status: 'healthy',
    sourceId: 'src_frontend_bff',
    metrics: [
      {
        label: 'Requests',
        value: '128 rps',
        tooltip: 'Average rate of incoming HTTP requests',
        series: [9, 10, 12, 13, 14, 12, 11, 15, 14, 12, 11, 10],
      },
      {
        label: 'Errors',
        value: '0.08%',
        tooltip: 'Percentage of incoming requests that returned an error',
        series: [0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0],
      },
      {
        label: 'Duration',
        value: '612 ms',
        tooltip: 'Average time to respond to an incoming request',
        series: [7, 9, 10, 12, 13, 12, 11, 14, 13, 11, 10, 9],
      },
    ],
    spans: [
      {
        id: 'span-root-dashboard',
        parentId: null,
        title: 'GET /dashboard/home',
        service: 'frontend-bff',
        kind: 'server',
        startNs: 0,
        durationNs: 612,
        startLabel: '0 ms',
        durationLabel: '612 ms',
        status: 'ok',
        summary: 'Builds the home dashboard payload by fanning out to multiple backend services in parallel.',
        namespace: 'prod-web',
        pod: 'frontend-bff-6f6ffdb7db-rb8pj',
        container: 'frontend-bff',
        runtime: 'nodejs 22',
        host: 'ip-10-30-42-90.ec2.internal',
        attributes: {
          'http.method': 'GET',
          'http.route': '/dashboard/home',
          'http.status_code': 200,
          'viewer.id': 'usr_20044',
        },
        logs: [
          {
            id: 'log-dashboard-root-1',
            type: 'log',
            timestamp: '2026-03-26 22:12:11.022 UTC',
            badge: 'Log',
            level: 'info',
            service: 'frontend-bff',
            message: 'Started home dashboard aggregation request.',
            details: {
              region: 'eu-west-1',
              experiment: 'dashboard-v3',
            },
          },
        ],
      },
      {
        id: 'span-dashboard-auth',
        parentId: 'span-root-dashboard',
        title: 'resolve session and entitlements',
        service: 'auth-service',
        kind: 'client',
        startNs: 12,
        durationNs: 84,
        startLabel: '12 ms',
        durationLabel: '84 ms',
        status: 'ok',
        summary: 'Loads user session metadata and product entitlements.',
        host: 'auth-service.internal',
        destination: 'auth/entitlements',
        attributes: {
          'rpc.system': 'grpc',
          'rpc.service': 'auth.SessionService',
        },
        logs: [],
      },
      {
        id: 'span-dashboard-alerts',
        parentId: 'span-root-dashboard',
        title: 'load active alerts',
        service: 'alerts-api',
        kind: 'client',
        startNs: 32,
        durationNs: 206,
        startLabel: '32 ms',
        durationLabel: '206 ms',
        status: 'ok',
        summary: 'Fetches unresolved alerts and incident summaries.',
        host: 'alerts-api.internal',
        destination: 'alerts/list',
        attributes: {
          'http.method': 'POST',
          'http.route': '/alerts/search',
        },
        logs: [
          {
            id: 'log-dashboard-alerts-1',
            type: 'log',
            timestamp: '2026-03-26 22:12:11.214 UTC',
            badge: 'Log',
            level: 'info',
            service: 'alerts-api',
            message: 'Fetched 9 active alerts and 2 incidents.',
            details: {
              alertCount: 9,
              incidentCount: 2,
            },
          },
        ],
      },
      {
        id: 'span-dashboard-usage',
        parentId: 'span-root-dashboard',
        title: 'load usage charts',
        service: 'usage-api',
        kind: 'client',
        startNs: 36,
        durationNs: 328,
        startLabel: '36 ms',
        durationLabel: '328 ms',
        status: 'ok',
        summary: 'Loads usage rollups and chart points for the dashboard widgets.',
        host: 'usage-api.internal',
        destination: 'usage/charts',
        attributes: {
          'http.method': 'POST',
          'http.route': '/usage/charts/query',
        },
        logs: [],
      },
      {
        id: 'span-dashboard-chart-transform',
        parentId: 'span-dashboard-usage',
        title: 'normalize chart series',
        service: 'usage-api',
        kind: 'worker',
        startNs: 172,
        durationNs: 102,
        startLabel: '172 ms',
        durationLabel: '102 ms',
        status: 'ok',
        summary: 'Transforms raw rollups into chart-ready buckets.',
        host: 'usage-api.internal',
        attributes: {
          buckets: 24,
          downsampled: true,
        },
        logs: [],
      },
      {
        id: 'span-dashboard-recommendations',
        parentId: 'span-root-dashboard',
        title: 'load recommendations',
        service: 'recommendation-api',
        kind: 'client',
        startNs: 54,
        durationNs: 148,
        startLabel: '54 ms',
        durationLabel: '148 ms',
        status: 'ok',
        summary: 'Fetches recommended dashboards and saved views.',
        host: 'recommendation-api.internal',
        destination: 'recommendations/home',
        attributes: {
          'http.method': 'GET',
          'http.route': '/recommendations/home',
        },
        logs: [],
      },
      {
        id: 'span-dashboard-render',
        parentId: 'span-root-dashboard',
        title: 'compose widget payload',
        service: 'frontend-bff',
        kind: 'worker',
        startNs: 404,
        durationNs: 126,
        startLabel: '404 ms',
        durationLabel: '126 ms',
        status: 'ok',
        summary: 'Merges all parallel subrequests into the final UI payload.',
        host: 'ip-10-30-42-90.ec2.internal',
        attributes: {
          widgets: 6,
          payloadSizeKb: 72,
        },
        logs: [
          {
            id: 'event-dashboard-render-1',
            type: 'event',
            timestamp: '2026-03-26 22:12:11.566 UTC',
            badge: 'Event',
            tags: ['render'],
            message: 'Dashboard widget payload finalized and cached for 15 seconds.',
            details: {
              cacheTtlSeconds: 15,
              widgets: 6,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'trace-cold-start',
    traceId: '6f2cc11bae8a4e9259b2000005dca870',
    title: 'POST /functions/report-export',
    service: 'report-export-fn',
    environment: 'staging',
    startedAt: '2026-03-26 22:18:41.667 UTC',
    durationLabel: '3.82 s',
    status: 'degraded',
    sourceId: 'src_report_export',
    metrics: [
      {
        label: 'Requests',
        value: '9 req/min',
        tooltip: 'Average rate of incoming export requests',
        series: [2, 3, 2, 4, 5, 4, 3, 5, 4, 3, 2, 3],
      },
      {
        label: 'Errors',
        value: '4.10%',
        tooltip: 'Percentage of export requests that time out or fail',
        series: [0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0],
      },
      {
        label: 'Duration',
        value: '3.82 s',
        tooltip: 'Average time to prepare and upload the export bundle',
        series: [12, 11, 15, 17, 18, 16, 15, 19, 18, 16, 15, 14],
      },
    ],
    spans: [
      {
        id: 'span-root-export',
        parentId: null,
        title: 'POST /functions/report-export',
        service: 'report-export-fn',
        kind: 'server',
        startNs: 0,
        durationNs: 3820,
        startLabel: '0 ms',
        durationLabel: '3.82 s',
        status: 'error',
        summary: 'Cold-started function bootstraps the export runtime, loads templates, and writes an archive to object storage.',
        namespace: 'staging-reports',
        pod: 'report-export-fn-01',
        container: 'report-export-fn',
        runtime: 'nodejs 22',
        host: 'aws-lambda-eu-west-1',
        attributes: {
          'faas.coldstart': true,
          'http.method': 'POST',
          'http.route': '/functions/report-export',
          'http.status_code': 504,
        },
        logs: [
          {
            id: 'log-root-export-1',
            type: 'log',
            timestamp: '2026-03-26 22:18:41.670 UTC',
            badge: 'Log',
            level: 'warn',
            service: 'report-export-fn',
            message: 'Cold start detected, loading export runtime and headless Chromium.',
            details: {
              memoryMb: 1024,
              coldStart: true,
              chromiumRevision: '125.0.0',
            },
          },
        ],
      },
      {
        id: 'span-export-bootstrap',
        parentId: 'span-root-export',
        title: 'bootstrap runtime',
        service: 'report-export-fn',
        kind: 'worker',
        startNs: 12,
        durationNs: 1180,
        startLabel: '12 ms',
        durationLabel: '1.18 s',
        status: 'ok',
        summary: 'Downloads the font pack, initializes Chromium, and warms PDF templates.',
        host: 'aws-lambda-eu-west-1',
        attributes: {
          'faas.coldstart': true,
          artifactsLoaded: 14,
        },
        logs: [],
      },
      {
        id: 'span-export-db',
        parentId: 'span-root-export',
        title: 'SELECT report data',
        service: 'reporting-db',
        kind: 'db',
        startNs: 1246,
        durationNs: 486,
        startLabel: '1.25 s',
        durationLabel: '486 ms',
        status: 'ok',
        summary: 'Loads report rows and attachments needed for the export bundle.',
        host: 'reporting-db.internal',
        attributes: {
          'db.system': 'postgresql',
          rows: 18442,
        },
        logs: [],
      },
      {
        id: 'span-export-render',
        parentId: 'span-root-export',
        title: 'render pdf pages',
        service: 'report-export-fn',
        kind: 'worker',
        startNs: 1768,
        durationNs: 1294,
        startLabel: '1.77 s',
        durationLabel: '1.29 s',
        status: 'ok',
        summary: 'Renders per-section pages and assembles them into one document.',
        host: 'aws-lambda-eu-west-1',
        attributes: {
          pages: 23,
          renderer: 'chromium-pdf',
        },
        logs: [],
      },
      {
        id: 'span-export-upload',
        parentId: 'span-root-export',
        title: 'PUT object storage export.zip',
        service: 'object-storage',
        kind: 'client',
        startNs: 3124,
        durationNs: 516,
        startLabel: '3.12 s',
        durationLabel: '516 ms',
        status: 'error',
        summary: 'Uploads the export archive to object storage and waits for a signed URL.',
        host: 's3.eu-west-1.amazonaws.com',
        destination: 'exports/report-export.zip',
        attributes: {
          'http.method': 'PUT',
          'http.status_code': 504,
          uploadSizeMb: 12.8,
        },
        logs: [
          {
            id: 'event-export-upload-1',
            type: 'event',
            timestamp: '2026-03-26 22:18:45.198 UTC',
            badge: 'Event',
            tags: ['timeout', 'upload'],
            message: 'Object storage upload exceeded the platform deadline before the signed URL returned.',
            details: {
              uploadSizeMb: 12.8,
              deadlineMs: 3500,
              retryable: true,
            },
          },
        ],
      },
    ],
  },
  {
    id: 'trace-streaming-chat',
    traceId: '7bd4a4441ae64a8db35f000006f1aa33',
    title: 'POST /api/chat/stream',
    service: 'chat-gateway',
    environment: 'production',
    startedAt: '2026-03-26 22:24:18.403 UTC',
    durationLabel: '8.64 s',
    status: 'healthy',
    sourceId: 'src_chat_gateway',
    metrics: [
      {
        label: 'Requests',
        value: '46 rps',
        tooltip: 'Average rate of incoming streaming chat requests',
        series: [5, 6, 7, 8, 7, 6, 7, 9, 8, 7, 6, 6],
      },
      {
        label: 'Errors',
        value: '0.61%',
        tooltip: 'Percentage of streaming chat requests that ended in error',
        series: [0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0],
      },
      {
        label: 'Duration',
        value: '8.64 s',
        tooltip: 'Average time from first token request to stream completion',
        series: [8, 9, 10, 12, 11, 10, 9, 13, 12, 10, 9, 8],
      },
    ],
    spans: [
      {
        id: 'span-root-chat',
        parentId: null,
        title: 'POST /api/chat/stream',
        service: 'chat-gateway',
        kind: 'server',
        startNs: 0,
        durationNs: 8640,
        startLabel: '0 ms',
        durationLabel: '8.64 s',
        status: 'ok',
        summary: 'Receives a chat prompt, loads retrieval context, fans out to moderation and model calls, then streams tokens back to the client.',
        namespace: 'prod-chat',
        pod: 'chat-gateway-5d8b6fcd55-kf2pr',
        container: 'chat-gateway',
        runtime: 'nodejs 22',
        host: 'ip-10-30-55-90.ec2.internal',
        attributes: {
          'http.method': 'POST',
          'http.route': '/api/chat/stream',
          'http.status_code': 200,
          model: 'claude-opus',
        },
        logs: [
          {
            id: 'log-root-chat-1',
            type: 'log',
            timestamp: '2026-03-26 22:24:18.408 UTC',
            badge: 'Log',
            level: 'info',
            service: 'chat-gateway',
            message: 'Accepted streaming chat request and created session ses_9ac4.',
            details: {
              sessionId: 'ses_9ac4',
              promptTokens: 2912,
              model: 'claude-opus',
            },
          },
        ],
      },
      {
        id: 'span-chat-auth',
        parentId: 'span-root-chat',
        title: 'authorize user and workspace',
        service: 'auth-service',
        kind: 'client',
        startNs: 12,
        durationNs: 92,
        startLabel: '12 ms',
        durationLabel: '92 ms',
        status: 'ok',
        summary: 'Verifies workspace membership and retrieves model entitlements.',
        host: 'auth-service.internal',
        destination: 'auth/session',
        attributes: {
          'rpc.system': 'grpc',
          'rpc.service': 'auth.WorkspaceService',
        },
        logs: [],
      },
      {
        id: 'span-chat-moderation',
        parentId: 'span-root-chat',
        title: 'moderate user prompt',
        service: 'safety-api',
        kind: 'client',
        startNs: 46,
        durationNs: 238,
        startLabel: '46 ms',
        durationLabel: '238 ms',
        status: 'ok',
        summary: 'Runs the prompt through moderation before the model request begins.',
        host: 'safety-api.internal',
        destination: 'safety/moderate',
        attributes: {
          'http.method': 'POST',
          'http.route': '/moderate',
        },
        logs: [],
      },
      {
        id: 'span-chat-rag',
        parentId: 'span-root-chat',
        title: 'retrieve semantic context',
        service: 'retrieval-api',
        kind: 'client',
        startNs: 64,
        durationNs: 684,
        startLabel: '64 ms',
        durationLabel: '684 ms',
        status: 'ok',
        summary: 'Builds embeddings and queries the vector index for top matching chunks.',
        host: 'retrieval-api.internal',
        destination: 'retrieval/search',
        attributes: {
          'http.method': 'POST',
          'http.route': '/retrieval/search',
          topK: 12,
        },
        logs: [
          {
            id: 'event-chat-rag-1',
            type: 'event',
            timestamp: '2026-03-26 22:24:19.018 UTC',
            badge: 'Event',
            tags: ['retrieval'],
            message: 'Retrieved 12 chunks across 3 documents for grounding.',
            details: {
              chunks: 12,
              documents: 3,
              vectorLatencyMs: 144,
            },
          },
        ],
      },
      {
        id: 'span-chat-model',
        parentId: 'span-root-chat',
        title: 'stream model response',
        service: 'ai-gateway',
        kind: 'client',
        startNs: 812,
        durationNs: 6940,
        startLabel: '812 ms',
        durationLabel: '6.94 s',
        status: 'ok',
        summary: 'Starts the upstream model stream and forwards deltas to the browser.',
        host: 'ai-gateway.internal',
        destination: 'llm/stream',
        attributes: {
          'http.method': 'POST',
          'http.route': '/llm/stream',
          model: 'claude-opus',
        },
        logs: [],
      },
      {
        id: 'span-chat-first-token',
        parentId: 'span-chat-model',
        title: 'await first token',
        service: 'ai-gateway',
        kind: 'worker',
        startNs: 812,
        durationNs: 1180,
        startLabel: '812 ms',
        durationLabel: '1.18 s',
        status: 'ok',
        summary: 'Tracks latency to first streamed token.',
        host: 'ai-gateway.internal',
        attributes: {
          phase: 'first-token',
          tokensReceived: 1,
        },
        logs: [],
      },
      {
        id: 'span-chat-stream-body',
        parentId: 'span-chat-model',
        title: 'forward token deltas',
        service: 'ai-gateway',
        kind: 'worker',
        startNs: 2034,
        durationNs: 5146,
        startLabel: '2.03 s',
        durationLabel: '5.15 s',
        status: 'ok',
        summary: 'Forwards token deltas while keeping the browser connection alive.',
        host: 'ai-gateway.internal',
        attributes: {
          phase: 'body',
          streamedTokens: 1640,
        },
        logs: [
          {
            id: 'log-chat-stream-body-1',
            type: 'log',
            timestamp: '2026-03-26 22:24:23.402 UTC',
            badge: 'Log',
            level: 'info',
            service: 'ai-gateway',
            message: 'Streaming response crossed 1.6k tokens without backpressure.',
            details: {
              streamedTokens: 1640,
              clientBackpressure: false,
            },
          },
        ],
      },
      {
        id: 'span-chat-persist',
        parentId: 'span-root-chat',
        title: 'persist conversation turn',
        service: 'conversation-store',
        kind: 'db',
        startNs: 7420,
        durationNs: 610,
        startLabel: '7.42 s',
        durationLabel: '610 ms',
        status: 'ok',
        summary: 'Writes the final assistant turn and token counts after the stream completes.',
        host: 'conversation-db.internal',
        attributes: {
          'db.system': 'postgresql',
          rowsWritten: 2,
        },
        logs: [],
      },
    ],
  },
]
