-- Generated by pnpm generate from src/schema.ts. Do not edit.
CREATE TABLE IF NOT EXISTS `bot_api_keys` (
	`app_id` text PRIMARY KEY,
	`gemini_api_key` text,
	`openai_api_key` text,
	`xai_api_key` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_bot_api_keys_app_id_bot_tokens_app_id_fk` FOREIGN KEY (`app_id`) REFERENCES `bot_tokens`(`app_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `bot_tokens` (
	`app_id` text PRIMARY KEY,
	`token` text NOT NULL,
	`bot_mode` text DEFAULT 'self_hosted' NOT NULL,
	`client_id` text,
	`client_secret` text,
	`proxy_url` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`last_used_at` datetime
);

CREATE TABLE IF NOT EXISTS `channel_agents` (
	`channel_id` text PRIMARY KEY,
	`agent_name` text NOT NULL,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_channel_agents_channel_id_channel_directories_channel_id_fk` FOREIGN KEY (`channel_id`) REFERENCES `channel_directories`(`channel_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `channel_directories` (
	`channel_id` text PRIMARY KEY,
	`directory` text NOT NULL,
	`channel_type` text NOT NULL,
	`guild_id` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `channel_mention_mode` (
	`channel_id` text PRIMARY KEY,
	`enabled` integer DEFAULT 0 NOT NULL,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_channel_mention_mode_channel_id_channel_directories_channel_id_fk` FOREIGN KEY (`channel_id`) REFERENCES `channel_directories`(`channel_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `channel_models` (
	`channel_id` text PRIMARY KEY,
	`model_id` text NOT NULL,
	`variant` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_channel_models_channel_id_channel_directories_channel_id_fk` FOREIGN KEY (`channel_id`) REFERENCES `channel_directories`(`channel_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `channel_verbosity` (
	`channel_id` text PRIMARY KEY,
	`verbosity` text DEFAULT 'tools_and_text' NOT NULL,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_channel_verbosity_channel_id_channel_directories_channel_id_fk` FOREIGN KEY (`channel_id`) REFERENCES `channel_directories`(`channel_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `channel_worktrees` (
	`channel_id` text PRIMARY KEY,
	`enabled` integer DEFAULT 0 NOT NULL,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_channel_worktrees_channel_id_channel_directories_channel_id_fk` FOREIGN KEY (`channel_id`) REFERENCES `channel_directories`(`channel_id`) ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `guild_categories` (
	`guild_id` text PRIMARY KEY,
	`category_id` text,
	`audio_category_id` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `scheduled_tasks` (
	`id` integer PRIMARY KEY AUTOINCREMENT,
	`status` text DEFAULT 'planned' NOT NULL,
	`schedule_kind` text NOT NULL,
	`run_at` datetime,
	`cron_expr` text,
	`timezone` text,
	`next_run_at` datetime NOT NULL,
	`running_started_at` datetime,
	`last_run_at` datetime,
	`last_error` text,
	`attempts` integer DEFAULT 0 NOT NULL,
	`payload_json` text NOT NULL,
	`prompt_preview` text NOT NULL,
	`channel_id` text,
	`thread_id` text,
	`session_id` text,
	`project_directory` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT `fk_scheduled_tasks_channel_id_channel_directories_channel_id_fk` FOREIGN KEY (`channel_id`) REFERENCES `channel_directories`(`channel_id`) ON UPDATE CASCADE ON DELETE SET NULL,
	CONSTRAINT `fk_scheduled_tasks_thread_id_thread_sessions_thread_id_fk` FOREIGN KEY (`thread_id`) REFERENCES `thread_sessions`(`thread_id`) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS `session_sleeps` (
	`session_id` text PRIMARY KEY,
	`wake_at` datetime NOT NULL,
	`reason` text,
	`status` text DEFAULT 'planned' NOT NULL,
	`delivery_id` text NOT NULL,
	`attempts` integer DEFAULT 0 NOT NULL,
	`last_attempt_at` datetime,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `thread_sessions` (
	`thread_id` text PRIMARY KEY,
	`session_id` text NOT NULL,
	`source` text DEFAULT 'kimaki' NOT NULL,
	`last_synced_name` text,
	`parent_session_id` text,
	`created_at` datetime DEFAULT CURRENT_TIMESTAMP,
	`updated_at` datetime DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS `scheduled_tasks_status_next_run_at_idx` ON `scheduled_tasks` (`status`,`next_run_at`);
CREATE INDEX IF NOT EXISTS `scheduled_tasks_channel_id_status_idx` ON `scheduled_tasks` (`channel_id`,`status`);
CREATE INDEX IF NOT EXISTS `scheduled_tasks_thread_id_status_idx` ON `scheduled_tasks` (`thread_id`,`status`);
CREATE INDEX IF NOT EXISTS `session_sleeps_status_wake_at_idx` ON `session_sleeps` (`status`,`wake_at`);
