// Start the bot when OpenCode starts. The bot writes <dataDir>/autostart.command
// on every start; the Kimaki OpenCode plugin opens it when no bot answers on
// the lock port:
//
//   kimaki start ──writes──▶ ~/.kimaki/autostart.command   (exec node <pkg>/dist/cli.js ...)
//                                       ▲
//   OpenCode loads plugin ──no /health on 29988──▶ open -g autostart.command
//                                                  (default terminal app, in background)
//
// The script exists only after a bot started with credentials, so a fresh
// install never opens a terminal with the onboarding prompts. It always runs
// dist/cli.js, also when the bot ran from src: keep dist built.
// Imported by the plugin (OpenCode process): node built-ins only, no logger.

import { spawn } from 'node:child_process'
import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

export const DEFAULT_LOCK_PORT = 29988

const SCRIPT_NAME = 'autostart.command'

const quote = (value: string) => `'${value.replaceAll("'", "'\\''")}'`

// <pkg>/dist/cli.js, from this file at <pkg>/{src,dist}/autostart.{ts,js}.
export function distCliEntry(): string {
  return path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', 'dist', 'cli.js')
}

// Windows has no autostart: it would need a .cmd script and `start`.
export async function writeAutostartScript({ dataDir, args }: { dataDir: string; args: readonly string[] }): Promise<Error | void> {
  if (process.platform === 'win32') return
  const file = path.join(dataDir, SCRIPT_NAME)
  const cli = distCliEntry()
  if (!fs.existsSync(cli)) return fs.promises.rm(file, { force: true }).catch((cause: Error) => cause)
  const command = [process.execPath, cli, '--data-dir', dataDir, ...args].map(quote).join(' ')
  const script = `#!/bin/sh\n# Generated by Kimaki on bot start. The Kimaki OpenCode plugin opens it when no bot runs.\nexec ${command}\n`
  return fs.promises.writeFile(file, script, { mode: 0o755 }).then(() => fs.promises.chmod(file, 0o755))
    .catch((cause: Error) => cause)
}

// Only the default install: HOME and the default port, never KIMAKI_* env.
// Agent shells export KIMAKI_DATA_DIR, so test OpenCode servers started from
// them would otherwise start the real bot. Test servers set HOME to a temp dir.
async function startIfStopped(): Promise<void> {
  const file = path.join(os.homedir(), '.kimaki', SCRIPT_NAME)
  if (!fs.existsSync(file)) return
  // Any answer means the port is taken (V2 or V1 bot).
  const running = await fetch(`http://127.0.0.1:${DEFAULT_LOCK_PORT}/health`, { signal: AbortSignal.timeout(2_000) })
    .then(() => true, () => false)
  if (running) return
  // macOS opens .command files in the default terminal app; -g keeps it in the background.
  const [command, args] = process.platform === 'darwin' ? ['open', ['-g', file]] as const : ['sh', [file]] as const
  const child = spawn(command, args, { detached: true, stdio: 'ignore' })
  child.on('error', () => undefined)
  child.unref()
}

// Once per OpenCode process: setup runs once per location and every reload
// re-imports the plugin, so module state would not dedupe. A bot the user
// stopped is not started again until OpenCode restarts.
const STARTED = Symbol.for('kimaki.autostart')

export function autostartBot(): void {
  if (process.platform === 'win32' || Reflect.get(globalThis, STARTED)) return
  Reflect.set(globalThis, STARTED, true)
  void startIfStopped().catch(() => undefined)
}
