// The bot registers the Kimaki plugin by writing plugins/kimaki/index.js into
// the global OpenCode config dir (opencode-server.ts installPluginShim). The
// test server starts with an empty config dir and a location that is already
// loaded, so the plugin arrives through OpenCode's watcher reload, like for a
// user whose service runs before the first Kimaki start.

import fs from 'node:fs'
import path from 'node:path'
import { afterAll, beforeAll, expect, test } from 'vitest'

import type { BotHandle } from './main.ts'
import {
  seedProjectChannel,
  startOpencodeTestServer,
  startTestBot,
  startTwin,
  tempDataDir,
  TEST_USER_ID,
  waitFor,
  waitForFooter,
  warmUp,
  type OpencodeTestServer,
  type TestTwin,
} from './test/harness.ts'

let server: OpencodeTestServer
let twin: TestTwin
let bot: BotHandle
let dataDir: string

beforeAll(async () => {
  dataDir = tempDataDir()
  ;[server, twin] = await Promise.all([startOpencodeTestServer(), startTwin()])
  await warmUp({ server })
  await seedProjectChannel({ dataDir, channelId: twin.channelId, guildId: twin.discord.guildId, directory: server.projectDirectory })
}, 60_000)

afterAll(async () => {
  await bot?.stop()
  await twin?.stop()
  await server?.stop()
  fs.rmSync(dataDir, { recursive: true, force: true })
})

test('bot start writes the plugin shim, OpenCode loads it, a restart does not rewrite it', async () => {
  const shim = path.join(server.configDir, 'plugins', 'kimaki', 'index.js')
  expect(fs.existsSync(shim)).toBe(false)
  const client = await server.client()
  const pluginStatus = async (id: string) => {
    const plugins = await client.plugin.list({ location: { directory: server.projectDirectory } })
    return plugins.data.find((plugin) => plugin.id === id)?.state.status ?? 'missing'
  }
  const kimakiStatus = () => pluginStatus('kimaki')
  expect(await kimakiStatus()).toBe('missing')

  bot = await startTestBot({ dataDir, twin, server })
  expect(fs.readFileSync(shim, 'utf8').replace(/file:\/\/\S+\/src\//, 'file:///<kimaki>/src/')).toMatchInlineSnapshot(`
    "// Generated by Kimaki on bot start. Loads the plugin of the running Kimaki install.
    export { default } from "file:///<kimaki>/src/plugin/index.ts"
    "
  `)
  // No wait here: the first session must itself wait until OpenCode's watcher loads the shim.
  await twin.discord.channel(twin.channelId).user(TEST_USER_ID).sendMessage({ content: 'plugin shim turn' })
  const thread = await twin.discord.channel(twin.channelId).waitForThread({ timeout: 8_000 })
  await waitForFooter({ discord: twin.discord, threadId: thread.id })
  expect(await kimakiStatus()).toBe('active')
  expect(await pluginStatus('kimaki-anthropic')).toBe('active')
  expect(await twin.discord.thread(thread.id).text()).toMatchInlineSnapshot(`
    "--- from: user (tommy)
    plugin shim turn
    --- from: assistant (TestBot)
    -# *using deterministic-provider/deterministic-v2 ⋅ build*
    ok
    -# *project ⋅ main ⋅ Ns ⋅ deterministic-v2*"
  `)

  const written = fs.statSync(shim).mtimeMs
  await bot.stop()
  bot = await startTestBot({ dataDir, twin, server })
  expect(fs.statSync(shim).mtimeMs).toBe(written)
}, 30_000)

// Plain OpenCode users list the anthropic plugin directory in opencode.json.
// The bot must then drop its shim, or OpenCode loads the ID twice and reports
// "Duplicate plugin ID" as a failed plugin.
test('anthropic plugin listed in opencode.json loads once, the bot removes its shim', async () => {
  const shimDirectory = path.join(server.configDir, 'plugins', 'kimaki-anthropic')
  expect(fs.existsSync(shimDirectory)).toBe(true)
  const pluginDirectory = path.join(import.meta.dirname, 'plugin', 'anthropic')
  fs.writeFileSync(
    path.join(server.configDir, 'opencode.jsonc'),
    `{\n  // standalone Claude Pro/Max login\n  "plugins": [${JSON.stringify(pluginDirectory)}],\n}\n`,
  )
  await bot.stop()
  bot = await startTestBot({ dataDir, twin, server })
  expect(fs.existsSync(shimDirectory)).toBe(false)
  expect(fs.existsSync(path.join(server.configDir, 'plugins', 'kimaki', 'index.js'))).toBe(true)

  const client = await server.client()
  const plugins = await waitFor({
    label: 'kimaki-anthropic loaded once from opencode.jsonc',
    check: async () => {
      const list = await client.plugin.list({ location: { directory: server.projectDirectory } })
      const anthropic = list.data.filter((plugin) => plugin.id === 'kimaki-anthropic')
      const fromConfig = anthropic.length === 1 && anthropic[0]?.state.status === 'active' && anthropic[0].source?.type === 'local' && anthropic[0].source.path.startsWith(pluginDirectory)
      return fromConfig && list.data
    },
  })
  expect(plugins.filter((plugin) => plugin.state.status === 'failed').map((plugin) => plugin.id)).toEqual([])
  expect(plugins.find((plugin) => plugin.id === 'kimaki')?.state.status).toBe('active')
}, 30_000)
